export type ShipRegister = {
  RowNum: number;
  NOREG: number;
  NOIMO: number;
  NMKPL: string;
  GRT: number;
  FLAG: string;
  TYSHP: string;
  STAT: string;
  status_compliance: string;
};

export type ShipRegisterDetail = {
  abre: string;
  bang: string;
  bers: string;
  blkls: string;
  blmkl: string;
  call: string;
  cool: string;
  coverage: string;
  doubleclass: string;
  dual: string;
  edual: string;
  exkpl: string;
  flag: string;
  iacs: string;
  jenis: string;
  kojen: string;
  kota: string;
  mat: string;
  nmkpl: string;
  noimo: string;
  noreg: string;
  notl1: string;
  notl2: string;
  notl3: string;
  notl4: string;
  notl5: string;
  notl6: string;
  notl7: string;
  notl8: string;
  notm1: string;
  notm2: string;
  notm3: string;
  notm4: string;
  notm5: string;
  notm6: string;
  pbkk: string;
  stat: string;
  stpen: string;
  tgkls: string;
  tgmkl: string;
  thkls: string;
  thmkl: string;
  thnk: string;
  tyshp: string;
  grt: string;
};

export type ShipRegisterHullData = {
  brt: string;
  nrt: string;
  dwt: string;
  dspl: string;
  loa: string;
  lbp: string;
  bmld: string;
  hmld: string;
  sarat: string;
  lt: string;
  nmgal: string;
  lgal: string;
  thba: string;
  tgnas: string;
  blnas: string;
  thnas: string;
  tglun: string;
  bllun: string;
  thlun: string;
  jmuat: string;
  jglad: string;
  jpal: string;
  upal: string;
  jskpj: string;
  jskml: string;
  pjfd: string;
  pjbd: string;
  pjbrd: string;
  jjhl: string;
  bjhl: string;
  tjhl: string;
  krjhl: string;
  drjhl: string;
  prjhl: string;
  trjhl: string;
  jjar: string;
  bjar: string;
  tjar: string;
  krjar: string;
  drjar: string;
  prjar: string;
  trjar: string;
  dtl: string;
  ptl: string;
  btl: string;
  jml: string;
  dml: string;
  pml: string;
  bml: string;
  jdk: string;
  jtm: string;
  jbm: string;
  albom: string;
};

export type PaginationInfo = {
  totalRecords: number;
  pageCount: number;
  pageSize: number;
}

export type ShipRegisterOwner = {
  nmfl1: string;
  nmfl2: string;
  almfl1: string;
  almfl2: string;
  kotafl: string;
};

export type ShipRegisterMachine = {
  jme: string;
  jmprop: string;
  jmb: string;
  sstr: string;
  rasgr: string;
  jpbb: string;
  tpbb: string;
  kdin: string;
  kcob: string;
  volt: string;
  arus: string;
  daya: string;
  jenme: string;
  ckme1: string;
  ckme2: string;
  dia: string;
  lang: string;
};